server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Vue Router history 模式需要这个
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API 请求转发到后端
    location /api/ {
        proxy_pass https://fitgenie.up.railway.app/;
        proxy_set_header Host api.fitgenie.up.railway.app;
    }
}